UPDATE game_event SET description='Sonnenwendfest' WHERE eventEntry=1;
UPDATE game_event SET description='Winterhauchfest' WHERE eventEntry=2;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wälder von Terokkar)' WHERE eventEntry=3;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Wald von Elwynn)' WHERE eventEntry=4;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt (Mulgore)' WHERE eventEntry=5;
UPDATE game_event SET description='Neujahr' WHERE eventEntry=6;
UPDATE game_event SET description='Mondfest' WHERE eventEntry=7;
UPDATE game_event SET description='Liebe liegt in der Luft ' WHERE eventEntry=8;
UPDATE game_event SET description='Kinderwoche' WHERE eventEntry=10;
UPDATE game_event SET description='Erntedankfest' WHERE eventEntry=11;
UPDATE game_event SET description='Schlotternächte' WHERE eventEntry=12;
UPDATE game_event SET description='Invasion der Elementare' WHERE eventEntry=13;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal Aufruf' WHERE eventEntry=14;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal' WHERE eventEntry=15;
UPDATE game_event SET description='Gurubashiarena' WHERE eventEntry=16;
UPDATE game_event SET description='Invasion der Geißel' WHERE eventEntry=17;
UPDATE game_event SET description='Ruf zu den Waffen: Alteractal!' WHERE eventEntry=18;
UPDATE game_event SET description='Ruf zu den Waffen: Kriegshymnenschlucht!' WHERE eventEntry=19;
UPDATE game_event SET description='Ruf zu den Waffen: Arathibecken!' WHERE eventEntry=20;
UPDATE game_event SET description='Ruf zu den Waffen: Auge des Sturms!' WHERE eventEntry=21;
UPDATE game_event SET description='Krieg von Ahn\'Qiraj' WHERE eventEntry=22;
UPDATE game_event SET description='Dunkelmond-Jahrmarkt wird aufgebaut (Wald von Elwynn)' WHERE eventEntry=23;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak' WHERE eventEntry=24;
UPDATE game_event SET description='Ruf zu den Waffen: Strand der Uralten' WHERE eventEntry=25;
UPDATE game_event SET description='Braufest' WHERE eventEntry=26;
UPDATE game_event SET description='Nacht beginnt' WHERE eventEntry=27;
UPDATE game_event SET description='Nobelgartenfest' WHERE eventEntry=28;
UPDATE game_event SET description='Rand des Wahnsinns, Gri\'lek' WHERE eventEntry=29;
UPDATE game_event SET description='Rand des Wahnsinns, Hazza\'rah' WHERE eventEntry=30;
UPDATE game_event SET description='Rand des Wahnsinns, Renataki' WHERE eventEntry=31;
UPDATE game_event SET description='Rand des Wahnsinns, Wushoolay' WHERE eventEntry=32;
UPDATE game_event SET description='Arenaturnier' WHERE eventEntry=33;
UPDATE game_event SET description='L70ETC Konzert' WHERE eventEntry=34;
UPDATE game_event SET description='Tag der Toten' WHERE eventEntry=35;
UPDATE game_event SET description='Anglerwettbewerb im Schlingendorntal Beginnt' WHERE eventEntry=36;
UPDATE game_event SET description='Pilgerfreudenfest' WHERE eventEntry=37;
UPDATE game_event SET description='Ruf zu den Waffen: Insel der Eroberung!' WHERE eventEntry=38;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Ankündigung)' WHERE eventEntry=39;
UPDATE game_event SET description='Angelwettstreit der Kalu\'ak (Endet)' WHERE eventEntry=40;