UPDATE gossip_texts SET content_loc3='[PH] SD2 unbekannter Text' WHERE entry=-3000000;
UPDATE gossip_texts SET content_loc3='Ich bin bereit, nach Burg Durnholde zu gehen.' WHERE entry=-3560000;
UPDATE gossip_texts SET content_loc3='Ich brauche ein Bündel Brandbomben.' WHERE entry=-3560001;
UPDATE gossip_texts SET content_loc3='Taretha kann dich nicht sehen, Thrall.' WHERE entry=-3560002;
UPDATE gossip_texts SET content_loc3='Die Situation ist recht kompliziert, Thrall. Es wäre das Beste für Euch, wenn Ihr nun in die Berge aufbrecht, bevor noch mehr von Schwarzmoors Männer hier auftauchen. Wir stellen sicher, dass Taretha in Sicherheit ist.' WHERE entry=-3560003;
UPDATE gossip_texts SET content_loc3='Wir sind bereit, Thrall.' WHERE entry=-3560004;
UPDATE gossip_texts SET content_loc3='Seltsamer Zauber?' WHERE entry=-3560005;
UPDATE gossip_texts SET content_loc3='Keine Sorge! Wir werden Euch hier herausholen, Taretha. Ich bezweifle, dass der Zauberer sich zu weit von hier entfernen würde.' WHERE entry=-3560006;
UPDATE gossip_texts SET content_loc3='Was glaubt Ihr, was sie vorhaben?' WHERE entry=-3595000;
UPDATE gossip_texts SET content_loc3='Ihr wollt, dass ich was tue?' WHERE entry=-3595001;
UPDATE gossip_texts SET content_loc3='Sehr wohl, Chromie' WHERE entry=-3595002;
UPDATE gossip_texts SET content_loc3='Warum wurde ich zu dieser speziellen Zeit und an diesen speziellen Ort zurückgeschickt?' WHERE entry=-3595003;
UPDATE gossip_texts SET content_loc3='Was war die Entscheidung?' WHERE entry=-3595004;
UPDATE gossip_texts SET content_loc3='Also, wie plant der ewige Drachenschwarm einzugreifen?' WHERE entry=-3595005;
UPDATE gossip_texts SET content_loc3='Sollten wir Ärger bekommen, so aktiviert die Kristalle, klar?' WHERE entry=-3608000;
UPDATE gossip_texts SET content_loc3='Bringt Eure Leute in Sicherheit, wir werden die Streitkräfte des blauen Drachenschwarms in Schacht halten.' WHERE entry=-3608001;
UPDATE gossip_texts SET content_loc3='Ja. Wir sind bereit für die Prüfungen, die vor uns liegen.' WHERE entry=-3649000;
