UPDATE points_of_interest SET icon_name='Gasthaus Zur Höhle des Löwen' WHERE entry=1;
UPDATE points_of_interest SET icon_name='Zaldimar Wefhellt' WHERE entry=2;
UPDATE points_of_interest SET icon_name='Bruder Wilhelm' WHERE entry=3;
UPDATE points_of_interest SET icon_name='Priesterin Josetta' WHERE entry=4;
UPDATE points_of_interest SET icon_name='Keryn Sylvius' WHERE entry=5;
UPDATE points_of_interest SET icon_name='Maximillian Raab' WHERE entry=6;
UPDATE points_of_interest SET icon_name='Lyria Du Lac' WHERE entry=7;
UPDATE points_of_interest SET icon_name='Alchemist Mallory' WHERE entry=8;
UPDATE points_of_interest SET icon_name='Schmied Argus' WHERE entry=9;
UPDATE points_of_interest SET icon_name='Tomas' WHERE entry=10;
UPDATE points_of_interest SET icon_name='Michelle Belle' WHERE entry=11;
UPDATE points_of_interest SET icon_name='Lee Braun' WHERE entry=12;
UPDATE points_of_interest SET icon_name='Inschriften von Sturmwind' WHERE entry=13;
UPDATE points_of_interest SET icon_name='Adele Fädler' WHERE entry=14;
UPDATE points_of_interest SET icon_name='Helene Pelzschneider' WHERE entry=15;
UPDATE points_of_interest SET icon_name='Eldrin' WHERE entry=16;
UPDATE points_of_interest SET icon_name='Erma' WHERE entry=17;
UPDATE points_of_interest SET icon_name='Auktionshaus von Sturmwind' WHERE entry=18;
UPDATE points_of_interest SET icon_name='Bank von Sturmwind' WHERE entry=19;
UPDATE points_of_interest SET icon_name='Hafen von Sturmwind' WHERE entry=20;
UPDATE points_of_interest SET icon_name='Die Tiefenbahn' WHERE entry=21;
UPDATE points_of_interest SET icon_name='Die güldene Rose' WHERE entry=22;
UPDATE points_of_interest SET icon_name='Greifenmeister von Sturmwind' WHERE entry=23;
UPDATE points_of_interest SET icon_name='Besucherzentrum von Sturmwind' WHERE entry=24;
UPDATE points_of_interest SET icon_name='Schlosser von Sturmwind' WHERE entry=25;
UPDATE points_of_interest SET icon_name='Jenova Steinschild' WHERE entry=26;
UPDATE points_of_interest SET icon_name='Woo Ping' WHERE entry=27;
UPDATE points_of_interest SET icon_name='Die Halle der Champions' WHERE entry=28;
UPDATE points_of_interest SET icon_name='Kampfmeister von Sturmwind' WHERE entry=29;
UPDATE points_of_interest SET icon_name='Barbier von Sturmwind' WHERE entry=30;
UPDATE points_of_interest SET icon_name='Inschriften von Sturmwind' WHERE entry=31;
UPDATE points_of_interest SET icon_name='Der Park' WHERE entry=32;
UPDATE points_of_interest SET icon_name='Jägerlodge' WHERE entry=33;
UPDATE points_of_interest SET icon_name='Magiersanktum' WHERE entry=34;
UPDATE points_of_interest SET icon_name='Kathedrale des Lichts' WHERE entry=35;
UPDATE points_of_interest SET icon_name='Schurkenhaus von Sturmwind' WHERE entry=36;
UPDATE points_of_interest SET icon_name='Weissagerin Umbrua' WHERE entry=37;
UPDATE points_of_interest SET icon_name='Zum geschlachteten Lamm' WHERE entry=38;
UPDATE points_of_interest SET icon_name='Kaserne von Sturmwind' WHERE entry=39;
UPDATE points_of_interest SET icon_name='Alchemiebedarf' WHERE entry=40;
UPDATE points_of_interest SET icon_name='Therum Tiefenschmied' WHERE entry=41;
UPDATE points_of_interest SET icon_name='Taverne Zum pfeifenden Schwein' WHERE entry=42;
UPDATE points_of_interest SET icon_name='Lucan Cordell' WHERE entry=43;
UPDATE points_of_interest SET icon_name='Lilliam Spindelfunks' WHERE entry=44;
UPDATE points_of_interest SET icon_name='Shaina Fuller' WHERE entry=45;
UPDATE points_of_interest SET icon_name='Arnold Leland' WHERE entry=46;
UPDATE points_of_interest SET icon_name='Der schützende Balg' WHERE entry=47;
UPDATE points_of_interest SET icon_name='Gelman Steinhand' WHERE entry=48;
UPDATE points_of_interest SET icon_name='Duncans Textilien' WHERE entry=49;
UPDATE points_of_interest SET icon_name='Auktionshaus von Eisenschmiede' WHERE entry=50;
UPDATE points_of_interest SET icon_name='Das Gewölbe' WHERE entry=51;
UPDATE points_of_interest SET icon_name='Die Tiefenbahn' WHERE entry=52;
UPDATE points_of_interest SET icon_name='Greifenmeister von Eisenschmiede' WHERE entry=53;
UPDATE points_of_interest SET icon_name='Besucherzentrum von Eisenschmiede' WHERE entry=54;
UPDATE points_of_interest SET icon_name='Steinfeuertaverne' WHERE entry=55;
UPDATE points_of_interest SET icon_name='Briefkasten von Eisenschmiede' WHERE entry=56;
UPDATE points_of_interest SET icon_name='Ulbrek Feuerhand' WHERE entry=57;
UPDATE points_of_interest SET icon_name='Bixi und Buliwyf' WHERE entry=58;
UPDATE points_of_interest SET icon_name='Kampfmeister von Eisenschmiede' WHERE entry=59;
UPDATE points_of_interest SET icon_name='Barbier von Eisenschmiede' WHERE entry=60;
UPDATE points_of_interest SET icon_name='Halle der Waffen' WHERE entry=61;
UPDATE points_of_interest SET icon_name='Halle der Mysterien' WHERE entry=62;
UPDATE points_of_interest SET icon_name='Schurkenlehrer von Eisenschmiede' WHERE entry=63;
UPDATE points_of_interest SET icon_name='Hexenmeisterlehrer von Eisenschmiede' WHERE entry=64;
UPDATE points_of_interest SET icon_name='Schamanenlehrer von Eisenschmiede' WHERE entry=65;
UPDATE points_of_interest SET icon_name='Brausefitz\' Tränke und Mischgetränke' WHERE entry=66;
UPDATE points_of_interest SET icon_name='Die große Schmiede' WHERE entry=67;
UPDATE points_of_interest SET icon_name='Zum Bronzekessel' WHERE entry=68;
UPDATE points_of_interest SET icon_name='Arkanarien Distelflaum' WHERE entry=69;
UPDATE points_of_interest SET icon_name='Heiler von Eisenschmiede' WHERE entry=70;
UPDATE points_of_interest SET icon_name='Reisender Angler' WHERE entry=71;
UPDATE points_of_interest SET icon_name='Inschriften von Eisenschmiede' WHERE entry=72;
UPDATE points_of_interest SET icon_name='Lederwaren Feinspindel' WHERE entry=73;
UPDATE points_of_interest SET icon_name='Tiefenbergbaugilde' WHERE entry=74;
UPDATE points_of_interest SET icon_name='Tuchmacherei Steinbraue' WHERE entry=75;
UPDATE points_of_interest SET icon_name='Brauerei Donnerbräu' WHERE entry=76;
UPDATE points_of_interest SET icon_name='Shelby Steinsplint' WHERE entry=77;
UPDATE points_of_interest SET icon_name='Grif Wildherz' WHERE entry=78;
UPDATE points_of_interest SET icon_name='Magis Funkelmantel' WHERE entry=79;
UPDATE points_of_interest SET icon_name='Azar Hammerkraft' WHERE entry=80;
UPDATE points_of_interest SET icon_name='Maxan Anvol' WHERE entry=81;
UPDATE points_of_interest SET icon_name='Hogral Bakkan' WHERE entry=82;
UPDATE points_of_interest SET icon_name='Gimrizz Schattenrad' WHERE entry=83;
UPDATE points_of_interest SET icon_name='Granis Flinkaxt' WHERE entry=84;
UPDATE points_of_interest SET icon_name='Tognus Funkenfeuer' WHERE entry=85;
UPDATE points_of_interest SET icon_name='Gremlock Pilsnor' WHERE entry=86;
UPDATE points_of_interest SET icon_name='Thamner Pol' WHERE entry=87;
UPDATE points_of_interest SET icon_name='Paxton Ganter' WHERE entry=88;
UPDATE points_of_interest SET icon_name='Auktionshaus Darnassus' WHERE entry=89;
UPDATE points_of_interest SET icon_name='Bank von Darnassus' WHERE entry=90;
UPDATE points_of_interest SET icon_name='Rut\'theran' WHERE entry=91;
UPDATE points_of_interest SET icon_name='Gildenmeister von Darnassus' WHERE entry=92;
UPDATE points_of_interest SET icon_name='Gasthaus von Darnassus' WHERE entry=93;
UPDATE points_of_interest SET icon_name='Briefkasten von Darnassus' WHERE entry=94;
UPDATE points_of_interest SET icon_name='Alassin' WHERE entry=95;
UPDATE points_of_interest SET icon_name='Ilyenia Mondfeuer' WHERE entry=96;
UPDATE points_of_interest SET icon_name='Kampfmeister von Darnassus' WHERE entry=97;
UPDATE points_of_interest SET icon_name='Druidenlehrer von Darnassus' WHERE entry=98;
UPDATE points_of_interest SET icon_name='Jägerlehrer von Darnassus' WHERE entry=99;
UPDATE points_of_interest SET icon_name='Schurkenlehrer von Darnassus' WHERE entry=100;
UPDATE points_of_interest SET icon_name='Die Terrasse der Krieger' WHERE entry=101;
UPDATE points_of_interest SET icon_name='Alchemielehrer von Darnassus' WHERE entry=102;
UPDATE points_of_interest SET icon_name='Kochkunstlehrer von Darnassus' WHERE entry=103;
UPDATE points_of_interest SET icon_name='Verzauberkunstlehrer von Darnassus' WHERE entry=104;
UPDATE points_of_interest SET icon_name='Lehrer für Erste Hilfe von Darnassus' WHERE entry=105;
UPDATE points_of_interest SET icon_name='Angellehrer von Darnassus' WHERE entry=106;
UPDATE points_of_interest SET icon_name='Inschriften von Darnassus' WHERE entry=107;
UPDATE points_of_interest SET icon_name='Lederverarbeitungslehrer von Darnassus' WHERE entry=108;
UPDATE points_of_interest SET icon_name='Kürschnerlehrer von Darnassus' WHERE entry=109;
UPDATE points_of_interest SET icon_name='Schneider von Darnassus' WHERE entry=110;
UPDATE points_of_interest SET icon_name='Gasthaus Dolanaar' WHERE entry=111;
UPDATE points_of_interest SET icon_name='Seriadne' WHERE entry=112;
UPDATE points_of_interest SET icon_name='Kal' WHERE entry=113;
UPDATE points_of_interest SET icon_name='Dazalar' WHERE entry=114;
UPDATE points_of_interest SET icon_name='Laurna Morgenglanz' WHERE entry=115;
UPDATE points_of_interest SET icon_name='Jannok Windsang' WHERE entry=116;
UPDATE points_of_interest SET icon_name='Kyra Windklinge' WHERE entry=117;
UPDATE points_of_interest SET icon_name='Cyndra Samtwisper' WHERE entry=118;
UPDATE points_of_interest SET icon_name='Zarrin' WHERE entry=119;
UPDATE points_of_interest SET icon_name='Alanna Rabenauge' WHERE entry=120;
UPDATE points_of_interest SET icon_name='Byancie' WHERE entry=121;
UPDATE points_of_interest SET icon_name='Malorne Messerblatt' WHERE entry=122;
UPDATE points_of_interest SET icon_name='Nadyia Schopfweber' WHERE entry=123;
UPDATE points_of_interest SET icon_name='Radnaal Schopfweber' WHERE entry=124;
UPDATE points_of_interest SET icon_name='Nadyia Schopfweber' WHERE entry=125;
UPDATE points_of_interest SET icon_name='Östlicher Kanalisationseingang von Dalaran' WHERE entry=126;
UPDATE points_of_interest SET icon_name='Westlicher Kanalisationseingang von Dalaran' WHERE entry=127;
UPDATE points_of_interest SET icon_name='Brunnen von Dalaran' WHERE entry=128;
UPDATE points_of_interest SET icon_name='Silberne Enklave von Dalaran' WHERE entry=129;
UPDATE points_of_interest SET icon_name='Sonnenhäschers Zuflucht von Dalaran' WHERE entry=130;
UPDATE points_of_interest SET icon_name='Nördliche Bank von Dalaran' WHERE entry=131;
UPDATE points_of_interest SET icon_name='Südliche Bank von Dalaran' WHERE entry=132;
UPDATE points_of_interest SET icon_name='Barbier von Dalaran' WHERE entry=133;
UPDATE points_of_interest SET icon_name='Flugmeister in Dalaran' WHERE entry=134;
UPDATE points_of_interest SET icon_name='Besucherzentrum von Dalaran' WHERE entry=135;
UPDATE points_of_interest SET icon_name='Gasthaus von Dalaran' WHERE entry=136;
UPDATE points_of_interest SET icon_name='Allianzgasthaus von Dalaran' WHERE entry=137;
UPDATE points_of_interest SET icon_name='Hordengasthaus von Dalaran' WHERE entry=138;
UPDATE points_of_interest SET icon_name='Schlosser von Dalaran' WHERE entry=139;
UPDATE points_of_interest SET icon_name='Krasus\' Landeplatz in Dalaran' WHERE entry=140;
UPDATE points_of_interest SET icon_name='Violette Zitadelle von Dalaran' WHERE entry=141;
UPDATE points_of_interest SET icon_name='Violette Festung von Dalaran' WHERE entry=142;
UPDATE points_of_interest SET icon_name='Handelsdistrikt von Dalaran' WHERE entry=143;
UPDATE points_of_interest SET icon_name='Antonidas\' Denkmal von Dalaran' WHERE entry=144;
UPDATE points_of_interest SET icon_name='Runenweberplatz von Dalaran' WHERE entry=145;
UPDATE points_of_interest SET icon_name='Abendruh in Dalaran' WHERE entry=146;
UPDATE points_of_interest SET icon_name='Friedhof von Dalaran' WHERE entry=147;
UPDATE points_of_interest SET icon_name='Inschriftenkundelehrer von Dalaran' WHERE entry=148;
UPDATE points_of_interest SET icon_name='Stallmeister in Dalaran' WHERE entry=149;
UPDATE points_of_interest SET icon_name='Magierlehrer von Dalaran' WHERE entry=150;
UPDATE points_of_interest SET icon_name='Alchemielehrer von Dalaran' WHERE entry=151;
UPDATE points_of_interest SET icon_name='Schmiedekunstlehrer von Dalaran' WHERE entry=152;
UPDATE points_of_interest SET icon_name='Verzauberkunstlehrer von Dalaran' WHERE entry=153;
UPDATE points_of_interest SET icon_name='Ingenieurskunstlehrer von Dalaran' WHERE entry=154;
UPDATE points_of_interest SET icon_name='Lehrer für Erste Hilfe von Dalaran' WHERE entry=155;
UPDATE points_of_interest SET icon_name='Anglerbrunnen von Dalaran' WHERE entry=156;
UPDATE points_of_interest SET icon_name='Kräuterkundelehrer von Dalaran' WHERE entry=157;
UPDATE points_of_interest SET icon_name='Juwelierskunstlehrer von Dalaran' WHERE entry=158;
UPDATE points_of_interest SET icon_name='Lederverarbeitungslehrer von Dalaran' WHERE entry=159;
UPDATE points_of_interest SET icon_name='Bergbaulehrer von Dalaran' WHERE entry=160;
UPDATE points_of_interest SET icon_name='Kürschnerlehrer von Dalaran' WHERE entry=161;
UPDATE points_of_interest SET icon_name='Schneiderleher von Dalaran' WHERE entry=162;
UPDATE points_of_interest SET icon_name='Stoffrüstung & Kleidung von Dalaran' WHERE entry=163;
UPDATE points_of_interest SET icon_name='Blumen von Dalaran' WHERE entry=164;
UPDATE points_of_interest SET icon_name='Fruchthändler von Dalaran' WHERE entry=165;
UPDATE points_of_interest SET icon_name='Gemischt- & Handwerksswarenladen von Dalaran' WHERE entry=166;
UPDATE points_of_interest SET icon_name='Haustierbedarf von Dalaran' WHERE entry=167;
UPDATE points_of_interest SET icon_name='Kuchen, Gebäck & Torten von Dalaran' WHERE entry=168;
UPDATE points_of_interest SET icon_name='Reagenzien von Dalaran' WHERE entry=169;
UPDATE points_of_interest SET icon_name='Spielzeugladen von Dalaran' WHERE entry=170;
UPDATE points_of_interest SET icon_name='Schmuckstücke von Dalaran' WHERE entry=171;
UPDATE points_of_interest SET icon_name='Nahkampfwaffen von Dalaran' WHERE entry=172;
UPDATE points_of_interest SET icon_name='Distanzwaffen von Dalaran' WHERE entry=173;
UPDATE points_of_interest SET icon_name='Stäbe & Zauberstäbe von Dalaran' WHERE entry=174;
UPDATE points_of_interest SET icon_name='Wein & Käse von Dalaran' WHERE entry=175;
UPDATE points_of_interest SET icon_name='Bank von Orgrimmar' WHERE entry=176;
UPDATE points_of_interest SET icon_name='Der Himmelsturm' WHERE entry=177;
UPDATE points_of_interest SET icon_name='Botschaft der Horde' WHERE entry=178;
UPDATE points_of_interest SET icon_name='Gasthaus von Orgrimmar' WHERE entry=179;
UPDATE points_of_interest SET icon_name='Briefkasten von Orgrimmar' WHERE entry=180;
UPDATE points_of_interest SET icon_name='Auktionshaus von Orgrimmar' WHERE entry=181;
UPDATE points_of_interest SET icon_name='Östlicher Zeppelinturm von Orgrimmar' WHERE entry=182;
UPDATE points_of_interest SET icon_name='Westlicher Zeppelinturm von Orgrimmar' WHERE entry=183;
UPDATE points_of_interest SET icon_name='Sayoc und Hanashi' WHERE entry=184;
UPDATE points_of_interest SET icon_name='Xon\'cha' WHERE entry=185;
UPDATE points_of_interest SET icon_name='Die Halle der Legenden' WHERE entry=186;
UPDATE points_of_interest SET icon_name='Kampfmeister von Orgrimmar' WHERE entry=187;
UPDATE points_of_interest SET icon_name='Barbier von Orgrimmar' WHERE entry=188;
UPDATE points_of_interest SET icon_name='Inschriften von Orgrimmar' WHERE entry=189;
UPDATE points_of_interest SET icon_name='Auktionator der Exodar' WHERE entry=190;
UPDATE points_of_interest SET icon_name='Bank der Exodar' WHERE entry=191;
UPDATE points_of_interest SET icon_name='Hippogryphenmeister der Exodar' WHERE entry=192;
UPDATE points_of_interest SET icon_name='Gildenmeister der Exodar' WHERE entry=193;
UPDATE points_of_interest SET icon_name='Gasthaus der Exodar' WHERE entry=194;
UPDATE points_of_interest SET icon_name='Briefkasten der Exodar' WHERE entry=195;
UPDATE points_of_interest SET icon_name='Stallmeister der Exodar' WHERE entry=196;
UPDATE points_of_interest SET icon_name='Waffenmeister der Exodar' WHERE entry=197;
UPDATE points_of_interest SET icon_name='Druidenlehrer der Exodar' WHERE entry=198;
UPDATE points_of_interest SET icon_name='Jägerlehrer der Exodar' WHERE entry=199;
UPDATE points_of_interest SET icon_name='Magierlehrer der Exodar' WHERE entry=200;
UPDATE points_of_interest SET icon_name='Paladinlehrer der Exodar' WHERE entry=201;
UPDATE points_of_interest SET icon_name='Priesterlehrer der Exodar' WHERE entry=202;
UPDATE points_of_interest SET icon_name='Schamanenlehrer der Exodar' WHERE entry=203;
UPDATE points_of_interest SET icon_name='Kriegerlehrer der Exodar' WHERE entry=204;
UPDATE points_of_interest SET icon_name='Alchemielehrer der Exodar' WHERE entry=205;
UPDATE points_of_interest SET icon_name='Schmiedekunstlehrer der Exodar' WHERE entry=206;
UPDATE points_of_interest SET icon_name='Verzauberer der Exodar' WHERE entry=207;
UPDATE points_of_interest SET icon_name='Ingenieurskunst der Exodar' WHERE entry=208;
UPDATE points_of_interest SET icon_name='Lehrer für Erste Hilfe der Exodar' WHERE entry=209;
UPDATE points_of_interest SET icon_name='Angellehrer der Exodar' WHERE entry=210;
UPDATE points_of_interest SET icon_name='Kräuterkundelehrer der Exodar' WHERE entry=211;
UPDATE points_of_interest SET icon_name='Inschriften der Exodar' WHERE entry=212;
UPDATE points_of_interest SET icon_name='Juwelenschleifer der Exodar' WHERE entry=213;
UPDATE points_of_interest SET icon_name='Lederverarbeitung der Exodar' WHERE entry=214;
UPDATE points_of_interest SET icon_name='Bergbaulehrer der Exodar' WHERE entry=215;
UPDATE points_of_interest SET icon_name='Kürschnerlehrer der Exodar' WHERE entry=216;
UPDATE points_of_interest SET icon_name='Schneider der Exodar' WHERE entry=217;
UPDATE points_of_interest SET icon_name='Koch der Exodar' WHERE entry=218;
UPDATE points_of_interest SET icon_name='Gastwirt der Azurwacht' WHERE entry=219;
UPDATE points_of_interest SET icon_name='Stallmeister der Azurwacht' WHERE entry=220;
UPDATE points_of_interest SET icon_name='Jägerlehrer der Azurwacht' WHERE entry=221;
UPDATE points_of_interest SET icon_name='Magierlehrer der Azurwacht' WHERE entry=222;
UPDATE points_of_interest SET icon_name='Paladinlehrer der Azurwacht' WHERE entry=223;
UPDATE points_of_interest SET icon_name='Priesterlehrer der Azurwacht' WHERE entry=224;
UPDATE points_of_interest SET icon_name='Schamanenlehrer der Azurwacht' WHERE entry=225;
UPDATE points_of_interest SET icon_name='Kriegerlehrer der Azurwacht' WHERE entry=226;
UPDATE points_of_interest SET icon_name='Alchemist der Azurwacht' WHERE entry=227;
UPDATE points_of_interest SET icon_name='Schmied von Odesyus\' Ankerplatz' WHERE entry=228;
UPDATE points_of_interest SET icon_name='Koch von Odesyus\' Ankerplatz' WHERE entry=229;
UPDATE points_of_interest SET icon_name='Ingenieurskunstlehrer der Azurwacht' WHERE entry=230;
UPDATE points_of_interest SET icon_name='Lehrer für Erste Hilfe der Azurwacht' WHERE entry=231;
UPDATE points_of_interest SET icon_name='Anglerin des Am\'menflusses' WHERE entry=232;
UPDATE points_of_interest SET icon_name='Kräuterkundiger der Azurwacht' WHERE entry=233;
UPDATE points_of_interest SET icon_name='Lederer der Tannenruhfeste' WHERE entry=234;
UPDATE points_of_interest SET icon_name='Bergbaulehrer der Azurwacht' WHERE entry=235;
UPDATE points_of_interest SET icon_name='Kürschner der Tannenruhfeste' WHERE entry=236;
UPDATE points_of_interest SET icon_name='Schneider von Odesyus\' Ankerplatz' WHERE entry=237;
UPDATE points_of_interest SET icon_name='Krunn' WHERE entry=238;
UPDATE points_of_interest SET icon_name='Mishiki' WHERE entry=239;
UPDATE points_of_interest SET icon_name='Lau\'Tiki' WHERE entry=240;
UPDATE points_of_interest SET icon_name='Rawrk' WHERE entry=241;
UPDATE points_of_interest SET icon_name='Mukdrak' WHERE entry=242;
UPDATE points_of_interest SET icon_name='Dwukk' WHERE entry=243;
UPDATE points_of_interest SET icon_name='Miao\'zan' WHERE entry=244;
UPDATE points_of_interest SET icon_name='Tarshaw Raunarbe' WHERE entry=245;
UPDATE points_of_interest SET icon_name='Dhugru Blutgier' WHERE entry=246;
UPDATE points_of_interest SET icon_name='Swart' WHERE entry=247;
UPDATE points_of_interest SET icon_name='Kaplak' WHERE entry=248;
UPDATE points_of_interest SET icon_name='Tai\'jin' WHERE entry=249;
UPDATE points_of_interest SET icon_name='Un\'Thuwa' WHERE entry=250;
UPDATE points_of_interest SET icon_name='Thotar' WHERE entry=251;
UPDATE points_of_interest SET icon_name='Shoja\'my' WHERE entry=252;
UPDATE points_of_interest SET icon_name='Gasthaus Klingenhügel' WHERE entry=253;
UPDATE points_of_interest SET icon_name='Schneiderlehrer von Unterstadt' WHERE entry=254;
UPDATE points_of_interest SET icon_name='Kürschnerlehrer von Unterstadt' WHERE entry=255;
UPDATE points_of_interest SET icon_name='Bergbaulehrer von Unterstadt' WHERE entry=256;
UPDATE points_of_interest SET icon_name='Lederverarbeitungslehrer von Unterstadt' WHERE entry=257;
UPDATE points_of_interest SET icon_name='Inschriften von Unterstadt' WHERE entry=258;
UPDATE points_of_interest SET icon_name='Kräuterkundelehrer von Unterstadt' WHERE entry=259;
UPDATE points_of_interest SET icon_name='Angellehrer von Unterstadt' WHERE entry=260;
UPDATE points_of_interest SET icon_name='Lehrer für Erste hilfe von Unterstadt' WHERE entry=261;
UPDATE points_of_interest SET icon_name='Ingenieurskunstlehrer von Unterstadt' WHERE entry=262;
UPDATE points_of_interest SET icon_name='Verzauberkunstlehrer von Unterstadt' WHERE entry=263;
UPDATE points_of_interest SET icon_name='Kochkunstlehrer von Unterstadt' WHERE entry=264;
UPDATE points_of_interest SET icon_name='Schmiedekunstlehrer von Unterstadt' WHERE entry=265;
UPDATE points_of_interest SET icon_name='Das Apothekarium' WHERE entry=266;
UPDATE points_of_interest SET icon_name='Kriegerlehrer von Unterstadt' WHERE entry=267;
UPDATE points_of_interest SET icon_name='Hexenmeisterlehrer von Unterstadt' WHERE entry=268;
UPDATE points_of_interest SET icon_name='Schurkenlehrer von Unterstadt' WHERE entry=269;
UPDATE points_of_interest SET icon_name='Priesterlehrer von Unterstadt' WHERE entry=270;
UPDATE points_of_interest SET icon_name='Champion Cyssa Dämmerrose' WHERE entry=271;
UPDATE points_of_interest SET icon_name='Magierlehrer von Unterstadt' WHERE entry=272;
UPDATE points_of_interest SET icon_name='Teppelin von Unterstadt' WHERE entry=273;
UPDATE points_of_interest SET icon_name='Archibald' WHERE entry=274;
UPDATE points_of_interest SET icon_name='Anya Maulray' WHERE entry=275;
UPDATE points_of_interest SET icon_name='Briefkasten von Unterstadt' WHERE entry=276;
UPDATE points_of_interest SET icon_name='Schlosser von Unterstadt' WHERE entry=277;
UPDATE points_of_interest SET icon_name='Gasthaus von Unterstadt' WHERE entry=278;
UPDATE points_of_interest SET icon_name='Gildenmeister von Unterstadt' WHERE entry=279;
UPDATE points_of_interest SET icon_name='Kampfmeister von unterstadt' WHERE entry=280;
UPDATE points_of_interest SET icon_name='Fledermausführer von Unterstadt' WHERE entry=281;
UPDATE points_of_interest SET icon_name='Barbier von Unterstadt' WHERE entry=282;
UPDATE points_of_interest SET icon_name='Bank von Unterstadt' WHERE entry=283;
UPDATE points_of_interest SET icon_name='Auktionshaus von Unterstadt' WHERE entry=284;
UPDATE points_of_interest SET icon_name='Bowen Brisboise' WHERE entry=285;
UPDATE points_of_interest SET icon_name='Rand Rhobart' WHERE entry=286;
UPDATE points_of_interest SET icon_name='Shelene Rhobart' WHERE entry=287;
UPDATE points_of_interest SET icon_name='Faruza' WHERE entry=288;
UPDATE points_of_interest SET icon_name='Clyde Kellen' WHERE entry=289;
UPDATE points_of_interest SET icon_name='Schwester Neela' WHERE entry=290;
UPDATE points_of_interest SET icon_name='Vance Niederglimm' WHERE entry=291;
UPDATE points_of_interest SET icon_name='Carolai Anise' WHERE entry=292;
UPDATE points_of_interest SET icon_name='Austil de Mon' WHERE entry=293;
UPDATE points_of_interest SET icon_name='Rupert Boch' WHERE entry=294;
UPDATE points_of_interest SET icon_name='Marion Kall' WHERE entry=295;
UPDATE points_of_interest SET icon_name='Morganus' WHERE entry=296;
UPDATE points_of_interest SET icon_name='Dunkler Kleriker Beryll' WHERE entry=297;
UPDATE points_of_interest SET icon_name='Cain Feuerlied' WHERE entry=298;
UPDATE points_of_interest SET icon_name='Taverne Zur Galgenschlinge' WHERE entry=299;
UPDATE points_of_interest SET icon_name='Zeppelin von Donnerfels' WHERE entry=300;
UPDATE points_of_interest SET icon_name='Rüstungsschmiede von Donnerfels' WHERE entry=301;
UPDATE points_of_interest SET icon_name='Mooranta' WHERE entry=302;
UPDATE points_of_interest SET icon_name='Steinhufgeologie' WHERE entry=303;
UPDATE points_of_interest SET icon_name='Rüstungsschmiede von Donnerfels' WHERE entry=304;
UPDATE points_of_interest SET icon_name='Inschriften von Donnerfels' WHERE entry=305;
UPDATE points_of_interest SET icon_name='Ganzheitliche kräuterkunde' WHERE entry=306;
UPDATE points_of_interest SET icon_name='Gipfelbergs Köder und Ausrüstung' WHERE entry=307;
UPDATE points_of_interest SET icon_name='Spirituelle Heilung' WHERE entry=308;
UPDATE points_of_interest SET icon_name='Morgenwandlers Verzauberungen' WHERE entry=309;
UPDATE points_of_interest SET icon_name='Askas Küche' WHERE entry=310;
UPDATE points_of_interest SET icon_name='Karns Schmiede' WHERE entry=311;
UPDATE points_of_interest SET icon_name='Benas Alchemie' WHERE entry=312;
UPDATE points_of_interest SET icon_name='Jägerhalle' WHERE entry=313;
UPDATE points_of_interest SET icon_name='Halle der Geister' WHERE entry=314;
UPDATE points_of_interest SET icon_name='Teiche der Visionen' WHERE entry=315;
UPDATE points_of_interest SET icon_name='Halle der Ältesten' WHERE entry=316;
UPDATE points_of_interest SET icon_name='Kampfmeister von Donnerfels' WHERE entry=317;
UPDATE points_of_interest SET icon_name='Bulrug' WHERE entry=318;
UPDATE points_of_interest SET icon_name='Ansekhwa' WHERE entry=319;
UPDATE points_of_interest SET icon_name='Auktionshaus von Donnerfels' WHERE entry=320;
UPDATE points_of_interest SET icon_name='Briefkasten von Donnerfels' WHERE entry=321;
UPDATE points_of_interest SET icon_name='Gasthaus von Donnerfels' WHERE entry=322;
UPDATE points_of_interest SET icon_name='Informationen der Stadtverwaltung von Donnerfels' WHERE entry=323;
UPDATE points_of_interest SET icon_name='Windreiterhorst' WHERE entry=324;
UPDATE points_of_interest SET icon_name='Bank von Donnerfels' WHERE entry=325;
UPDATE points_of_interest SET icon_name='Yonn Pelzscherer' WHERE entry=326;
UPDATE points_of_interest SET icon_name='Chaw Starkfell' WHERE entry=327;
UPDATE points_of_interest SET icon_name='Inschriften von Donnerfels' WHERE entry=328;
UPDATE points_of_interest SET icon_name='Uthan Stillwasser' WHERE entry=329;
UPDATE points_of_interest SET icon_name='Vira Junghuf' WHERE entry=330;
UPDATE points_of_interest SET icon_name='Pyall Leisetreter' WHERE entry=331;
UPDATE points_of_interest SET icon_name='Krang Steinhuf' WHERE entry=332;
UPDATE points_of_interest SET icon_name='Narm Himmelsjäger' WHERE entry=334;
UPDATE points_of_interest SET icon_name='Yaw Scharfmähne' WHERE entry=335;
UPDATE points_of_interest SET icon_name='Gennia Runentotem' WHERE entry=336;
UPDATE points_of_interest SET icon_name='Seikwa' WHERE entry=337;
UPDATE points_of_interest SET icon_name='Gasthaus der Bluthufe' WHERE entry=338;
UPDATE points_of_interest SET icon_name='Yarr Hammerstein' WHERE entry=339;
UPDATE points_of_interest SET icon_name='Wirtshaus von Shattrath' WHERE entry=340;
UPDATE points_of_interest SET icon_name='Taxi von Shattrath' WHERE entry=341;
UPDATE points_of_interest SET icon_name='Alchemist von Shattrath' WHERE entry=342;
UPDATE points_of_interest SET icon_name='Rüstungs- und Waffenmacher von Shattrath' WHERE entry=343;
UPDATE points_of_interest SET icon_name='Koch von Shattrath' WHERE entry=344;
UPDATE points_of_interest SET icon_name='Verzauberer von Shattrath' WHERE entry=345;
UPDATE points_of_interest SET icon_name='Erste Hilfe von Shattrath' WHERE entry=346;
UPDATE points_of_interest SET icon_name='Juwelenschleifer von Shattrath' WHERE entry=347;
UPDATE points_of_interest SET icon_name='Lederer von Shattrath' WHERE entry=348;
UPDATE points_of_interest SET icon_name='Kürschner von Shattrath' WHERE entry=349;
UPDATE points_of_interest SET icon_name='Manawebrahmen von Shattrath' WHERE entry=350;
UPDATE points_of_interest SET icon_name='Alchemielabor von Shattrath' WHERE entry=351;
UPDATE points_of_interest SET icon_name='Bank der Aldor von Shattrath' WHERE entry=352;
UPDATE points_of_interest SET icon_name='Bank der Seher von Shattrath' WHERE entry=353;
UPDATE points_of_interest SET icon_name='Gasthaus der Aldor von Shattrath' WHERE entry=354;
UPDATE points_of_interest SET icon_name='Gasthaus der Seher von Shattrath' WHERE entry=355;
UPDATE points_of_interest SET icon_name='Stall der Aldor von Shattrath' WHERE entry=356;
UPDATE points_of_interest SET icon_name='Stall der Seher von Shattrath' WHERE entry=357;
UPDATE points_of_interest SET icon_name='Kampfmeister der Allianz von Shattrath' WHERE entry=358;
UPDATE points_of_interest SET icon_name='Kampfmeister der Horde von Shattrath' WHERE entry=359;
UPDATE points_of_interest SET icon_name='Arenakampfmeister von Shattrath' WHERE entry=360;
UPDATE points_of_interest SET icon_name='Edelsteinhändler der Aldor' WHERE entry=361;
UPDATE points_of_interest SET icon_name='Edelsteinhändler der Seher' WHERE entry=362;
UPDATE points_of_interest SET icon_name='Leder- & Kettenrüstung von Dalaran' WHERE entry=365;
UPDATE points_of_interest SET icon_name='Tempel des Mondes' WHERE entry=364;
UPDATE points_of_interest SET icon_name='Kräuterkundige Pomeroy' WHERE entry=363;
UPDATE points_of_interest SET icon_name='Plattenrüstung & Schilde in Dalaran' WHERE entry=366;
UPDATE points_of_interest SET icon_name='Auktionshaus von Silbermond' WHERE entry=367;
UPDATE points_of_interest SET icon_name='Auktionshaus von Silbermond' WHERE entry=368;
UPDATE points_of_interest SET icon_name='Bank von Silbermond' WHERE entry=369;
UPDATE points_of_interest SET icon_name='Bank von Silbermond' WHERE entry=370;
UPDATE points_of_interest SET icon_name='Flugmeister von Silbermond' WHERE entry=371;
UPDATE points_of_interest SET icon_name='Gildenhaus von Silbermond' WHERE entry=372;
UPDATE points_of_interest SET icon_name='Gasthaus von Silbermond' WHERE entry=373;
UPDATE points_of_interest SET icon_name='Gasthaus von Silbermond' WHERE entry=374;
UPDATE points_of_interest SET icon_name='Briefkasten von Silbermond' WHERE entry=375;
UPDATE points_of_interest SET icon_name='Stallmeister von Silbermond' WHERE entry=376;
UPDATE points_of_interest SET icon_name='Waffenmeister von Silbermond' WHERE entry=377;
UPDATE points_of_interest SET icon_name='Kampfmeister von Silbermond' WHERE entry=378;
UPDATE points_of_interest SET icon_name='Druidenlehrer von Silbermond' WHERE entry=379;
UPDATE points_of_interest SET icon_name='Jägerlehrer von Silbermond' WHERE entry=380;
UPDATE points_of_interest SET icon_name='Magielehrer von Silbermond' WHERE entry=381;
UPDATE points_of_interest SET icon_name='Paladinlehrer von Silbermond' WHERE entry=382;
UPDATE points_of_interest SET icon_name='Priesterlehrer von Silbermond' WHERE entry=383;
UPDATE points_of_interest SET icon_name='Schurkenlehrer von Silbermond' WHERE entry=384;
UPDATE points_of_interest SET icon_name='Hexenmeisterlehrer von Silbermond' WHERE entry=385;
UPDATE points_of_interest SET icon_name='Alchemie von Silbermond' WHERE entry=386;
UPDATE points_of_interest SET icon_name='Schmiedekunst von Silbermond' WHERE entry=387;
UPDATE points_of_interest SET icon_name='Kochen in Silbermond' WHERE entry=388;
UPDATE points_of_interest SET icon_name='Verzauberkunst von Silbermond' WHERE entry=389;
UPDATE points_of_interest SET icon_name='Ingenieurskunst von Silbermond' WHERE entry=390;
UPDATE points_of_interest SET icon_name='Erste Hilfe von Silbermond' WHERE entry=391;
UPDATE points_of_interest SET icon_name='Angeln von Silbermond' WHERE entry=392;
UPDATE points_of_interest SET icon_name='Kräuterkunde von Silbermond' WHERE entry=393;
UPDATE points_of_interest SET icon_name='Inschriften von Silbermond' WHERE entry=394;
UPDATE points_of_interest SET icon_name='Juwelenschleifen von Silbermond' WHERE entry=395;
UPDATE points_of_interest SET icon_name='Lederverarbeitung von Silbermond' WHERE entry=396;
UPDATE points_of_interest SET icon_name='Bergbau von Silbermond' WHERE entry=397;
UPDATE points_of_interest SET icon_name='Kürschnerei von Silbermond' WHERE entry=398;
UPDATE points_of_interest SET icon_name='Schneiderei von Silbermond' WHERE entry=399;
UPDATE points_of_interest SET icon_name='Manawebrahmen von Silbermond' WHERE entry=400;
UPDATE points_of_interest SET icon_name='Gastwirt vom Falkenplatz' WHERE entry=401;
UPDATE points_of_interest SET icon_name='Stallmeister vom Falkenplatz' WHERE entry=402;
UPDATE points_of_interest SET icon_name='Jägerlehrer vom Falkenplatz' WHERE entry=403;
UPDATE points_of_interest SET icon_name='Magielehrer vom Falkenplatz' WHERE entry=404;
UPDATE points_of_interest SET icon_name='Paladinlehrer vom Falkenplatz' WHERE entry=405;
UPDATE points_of_interest SET icon_name='Priesterlehrer vom Falkenplatz' WHERE entry=406;
UPDATE points_of_interest SET icon_name='Schurkenlehrer vom Falkenplatz' WHERE entry=407;
UPDATE points_of_interest SET icon_name='Hexenmeisterlehrer vom Falkenplatz' WHERE entry=408;
UPDATE points_of_interest SET icon_name='Alchemist von Saltherils Hafen' WHERE entry=409;
UPDATE points_of_interest SET icon_name='Schmied der Zuflucht der Weltenwanderer' WHERE entry=410;
UPDATE points_of_interest SET icon_name='Koch vom Falkenplatz' WHERE entry=411;
UPDATE points_of_interest SET icon_name='Verzauberer von Saltherils Hafen' WHERE entry=412;
UPDATE points_of_interest SET icon_name='Lehrer für Erste Hilfe vom Falkenplatz' WHERE entry=413;
UPDATE points_of_interest SET icon_name='Kräuterkundiger von Saltherils Hafen' WHERE entry=414;
UPDATE points_of_interest SET icon_name='Juwelenschleifer vom Falkenplatz' WHERE entry=415;
UPDATE points_of_interest SET icon_name='Lederer des Immersangwalds' WHERE entry=416;
UPDATE points_of_interest SET icon_name='Kürschner des Immersangwalds' WHERE entry=417;
UPDATE points_of_interest SET icon_name='Schneider von Saltherils Hafen' WHERE entry=418;
UPDATE points_of_interest SET icon_name='Gerätehandel Sprungspindel' WHERE entry=419;
UPDATE points_of_interest SET icon_name='Jägerhalle von Orgrimmar' WHERE entry=420;
UPDATE points_of_interest SET icon_name='Dunkeldornenlodge' WHERE entry=421;
UPDATE points_of_interest SET icon_name='Geisterlodge' WHERE entry=422;
UPDATE points_of_interest SET icon_name='Thralls Festung' WHERE entry=423;
UPDATE points_of_interest SET icon_name='Bruderschaft der Schattenläufer' WHERE entry=424;
UPDATE points_of_interest SET icon_name='Dunkelfeuerenklave' WHERE entry=425;
UPDATE points_of_interest SET icon_name='Halle der Kriegerhelden' WHERE entry=426;
UPDATE points_of_interest SET icon_name='Yelmaks Alchemie und Tränke' WHERE entry=427;
UPDATE points_of_interest SET icon_name='Der brennende Amboss' WHERE entry=428;
UPDATE points_of_interest SET icon_name='Borstans Feuergrube' WHERE entry=429;
UPDATE points_of_interest SET icon_name='Godans Runenarbeiten' WHERE entry=430;
UPDATE points_of_interest SET icon_name='Noggs Meistermaschinen' WHERE entry=431;
UPDATE points_of_interest SET icon_name='Der Stärkste überlebt' WHERE entry=432;
UPDATE points_of_interest SET icon_name='Lumaks Angeln' WHERE entry=433;
UPDATE points_of_interest SET icon_name='Jandis Arboretum' WHERE entry=434;
UPDATE points_of_interest SET icon_name='Bergbauunternehmen Rotschlucht' WHERE entry=435;
UPDATE points_of_interest SET icon_name='Kodolederer' WHERE entry=436;
UPDATE points_of_interest SET icon_name='Magars Tuchwaren' WHERE entry=437;
UPDATE points_of_interest SET icon_name='Magielehrer von Darnassus' WHERE entry=438;
UPDATE points_of_interest SET icon_name='Paladinlehrer von Darnassus' WHERE entry=439;
UPDATE points_of_interest SET icon_name='Kräuterkundelehrer von Darnassus' WHERE entry=440;
UPDATE points_of_interest SET icon_name='Kampfmeister der Exodar' WHERE entry=441;
UPDATE points_of_interest SET icon_name='Arenakampfmeister der Exodar' WHERE entry=442;
UPDATE points_of_interest SET icon_name='Arena in der Kanalisation von Dalaran' WHERE entry=443;
UPDATE points_of_interest SET icon_name='Bank in der Kanalisation von Dalaran' WHERE entry=444;
UPDATE points_of_interest SET icon_name='Gasthaus in der Kanalisation von Dalaran' WHERE entry=445;
UPDATE points_of_interest SET icon_name='Kanalisationstunnel von Dalaran' WHERE entry=446;
UPDATE points_of_interest SET icon_name='Händler in der Kanalisation von Dalaran' WHERE entry=447;