insert into `pool_template` (`entry`, `max_limit`, `description`) values('2000','25','Master Mineral Pool - Alterac Mountains (Inner Section)');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2001','25','Master Mineral Pool - Alterac Mountains (Outer Section)');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2002','25','Master Mineral Pool - Arathi Highlands (Main Section)');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2003','25','Master Mineral Pool - Arathi Highlands (Drywhisker Gorge)');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2004','25','Master Mineral Pool - Badlands');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2005','25','Master Mineral Pool - Blasted Lands');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2006','25','Master Mineral Pool - Blasted Lands (Garrison Armory) - Special Mineral GOs ONLY');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2007','25','Master Mineral Pool - Burning Steppes');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2008','25','Master Mineral Pool - Dun Morogh');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2009','25','Master Mineral Pool - Duskwood');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2010','25','Master Mineral Pool - Eastern Plaguelands');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2011','25','Master Mineral Pool - Elwynn Forest');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2012','25','Master Mineral Pool - Eversong Woods');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2013','25','Master Mineral Pool - Ghostlands');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2014','25','Master Mineral Pool - Hillsbrad Foothills (Main Section)');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2015','25','Master Mineral Pool - Hillsbrad Foothills (Higher Level Sections)');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2016','25','Master Mineral Pool - Hillsbrad Foothills (Azurelode Mine) - Special Mineral GOs ONLY');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2017','25','Master Mineral Pool - Isle of Quel\'Danas');
insert into `pool_template` (`entry`, `max_limit`, `description`) values('2018','25','Master Mineral Pool - Loch Modan');